import { MaintenanceRequest } from "../models/index.js";
import { sequelize } from "../db/sequelize.js";

const state={requests:new Map(),errors:new Map(),durations:[]};
function key(m,r,s){return m+"|"+r+"|"+s;}
export function metricsMiddleware(req,res,next){const started=process.hrtime.bigint();res.on("finish",()=>{const route=req.route?.path?req.baseUrl+req.route.path:req.path,k=key(req.method,route,res.statusCode);state.requests.set(k,(state.requests.get(k)||0)+1);if(res.statusCode>=400)state.errors.set(k,(state.errors.get(k)||0)+1);state.durations.push(Number(process.hrtime.bigint()-started)/1e9);if(state.durations.length>5000)state.durations.shift();});next();}
const esc=s=>String(s).replaceAll("\\","\\\\").replaceAll('"',"\\"");
const labels=(m,r,s)=>'method="'+esc(m)+'",route="'+esc(r)+'",status="'+s+'"';
export async function metricsText(){let out="# HELP http_requests_total Total HTTP requests\n# TYPE http_requests_total counter\n";for(const[k,v]of state.requests){const[m,r,s]=k.split("|");out+="http_requests_total{"+labels(m,r,s)+"} "+v+"\n";}out+="# HELP http_errors_total Total HTTP errors\n# TYPE http_errors_total counter\n";for(const[k,v]of state.errors){const[m,r,s]=k.split("|");out+="http_errors_total{"+labels(m,r,s)+"} "+v+"\n";}const count=state.durations.length,sum=state.durations.reduce((a,b)=>a+b,0);out+="# HELP http_request_duration_seconds_sum Total request duration in seconds\n# TYPE http_request_duration_seconds_sum counter\nhttp_request_duration_seconds_sum "+sum+"\nhttp_request_duration_seconds_count "+count+"\n";try{const statuses=await MaintenanceRequest.findAll({attributes:["status",[sequelize.fn("COUNT",sequelize.col("id")),"count"]],group:["status"],raw:true});out+="# HELP maintenance_requests_by_status Maintenance requests by status\n# TYPE maintenance_requests_by_status gauge\n";for(const row of statuses)out+='maintenance_requests_by_status{status="'+esc(row.status)+'"} '+row.count+"\n";const priorities=await MaintenanceRequest.findAll({attributes:["priority",[sequelize.fn("COUNT",sequelize.col("id")),"count"]],group:["priority"],raw:true});out+="# HELP maintenance_requests_by_priority Maintenance requests by priority\n# TYPE maintenance_requests_by_priority gauge\n";for(const row of priorities)out+='maintenance_requests_by_priority{priority="'+esc(row.priority)+'"} '+row.count+"\n";const[avg]=await sequelize.query('SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (h.changed_at - r.created_at))/3600),0) AS hours FROM maintenance_requests r JOIN request_status_history h ON h.request_id=r.id AND h.to_status=\'done\'');out+="# HELP maintenance_request_avg_close_hours Average hours from request creation to done\n# TYPE maintenance_request_avg_close_hours gauge\nmaintenance_request_avg_close_hours "+Number(avg[0]?.hours||0)+"\n";}catch{out+="# HELP caselab_business_metrics_available Whether database-backed business metrics are available\n# TYPE caselab_business_metrics_available gauge\ncaselab_business_metrics_available 0\n";}return out;}
